# -*- coding: utf-8 -*-
"""Alt_Mobility.inpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ovvs1yQqgIxMrLSWUYphyq07BVOWvDCW
"""

import pandas as pd

orders_df = pd.read_csv('/content/customer_orders.csv')
payments_df = pd.read_csv('/content/payments.csv')

print("Customer Orders Preview:")
print(orders_df.head())

print("\nPayments Preview:")
print(payments_df.head())

print("\nOrders Info:")
print(orders_df.info())

print("\nPayments Info:")
print(payments_df.info())

print("\nOrders Null_Value_count:")
print(orders_df.isnull().sum())

print("\nPayments Null_Value_count:")
print(payments_df.isnull().sum())

import sqlite3

conn = sqlite3.connect(':memory:')

orders_df.to_sql('orders', conn, index=False, if_exists='replace')
payments_df.to_sql('payments', conn, index=False, if_exists='replace')

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("\nSQL Tables Available:")
print(tables)

"""**1. Order and Sales Analysis**

a. Order Fulfillment Summary
"""

query = """
SELECT
    order_status,
    COUNT(*) AS order_count
FROM
    orders
GROUP BY
    order_status;
"""

result = pd.read_sql(query, conn)
print("Order Fulfillment Summary:")
print(result)

"""b. Monthly Sales Trends"""

query = """
SELECT
    strftime('%Y-%m', order_date) AS month,
    SUM(payment_amount) AS total_revenue
FROM
    orders
JOIN
    payments ON orders.order_id = payments.order_id
GROUP BY
    month
ORDER BY
    month;
"""
monthly_sales = pd.read_sql(query, conn)
print("Monthly Sales Trends:")
print(monthly_sales)

"""c. Average Order Value"""

query = """
SELECT
    AVG(order_amount) AS average_order_value,
    SUM(order_amount) AS total_sales,
    COUNT(order_id) AS total_orders
FROM orders;
"""
avg_order_value = pd.read_sql(query, conn)
print("\nAverage Order Value:")
print(avg_order_value)

"""**2. Customer Analysis**

a. Total Revenue Per Customer
"""

query = """
SELECT
    o.customer_id,
    SUM(p.payment_amount) AS total_paid
FROM
    payments p
JOIN
    orders o ON p.order_id = o.order_id
WHERE
    p.payment_status = 'completed'
GROUP BY
    o.customer_id
ORDER BY
    total_paid DESC;
"""

revenue_per_customer = pd.read_sql(query, conn)
print("Total Revenue Per Customer:")
print(revenue_per_customer.head())

"""b. Number of Orders per Customer/Repeat Orders"""

query = """
SELECT
    customer_id,
    COUNT(order_id) AS total_orders
FROM
    orders
GROUP BY
    customer_id
ORDER BY
    total_orders DESC;
"""

orders_per_customer = pd.read_sql(query, conn)
print("Number of Orders per Customer:")
print(orders_per_customer.head())

"""c. Comprehensive Customer Summary"""

query = """
SELECT
    o.customer_id,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(p.payment_amount) AS total_paid,
    ROUND(SUM(p.payment_amount) * 1.0 / COUNT(DISTINCT o.order_id), 2) AS avg_payment_per_order
FROM
    orders o
JOIN
    payments p ON o.order_id = p.order_id
WHERE
    p.payment_status = 'completed'
GROUP BY
    o.customer_id
ORDER BY
    total_paid DESC;
"""

customer_summary = pd.read_sql(query, conn)
print("Customer Summary:")
print(customer_summary.head())

"""d. Customer Segmentation"""

query_segmentation = """
SELECT
    customer_id,
    COUNT(order_id) AS total_orders,
    SUM(order_amount) AS total_spent,
    CASE
        WHEN COUNT(order_id) = 1 THEN 'One-time'
        WHEN COUNT(order_id) BETWEEN 2 AND 5 THEN 'Occasional'
        ELSE 'Frequent'
    END AS customer_segment
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC;
"""
customer_segmentation = pd.read_sql(query_segmentation, conn)
print("Customer Segmentation:")
print(customer_segmentation.head())

"""e. Trends in Customer Ordering Behavior"""

query_trends = """
SELECT
    strftime('%Y-%m', order_date) AS order_month,
    COUNT(order_id) AS total_orders,
    ROUND(AVG(order_amount), 2) AS avg_order_value
FROM orders
GROUP BY order_month
ORDER BY order_month;
"""
ordering_trends = pd.read_sql(query_trends, conn)
print("Ordering Trends Over Time:")
print(ordering_trends)

"""**3. Payment Status Analysis**

a. Payment Status Breakdown
"""

query = """
SELECT
    payment_status,
    COUNT(*) AS count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM payments), 2) AS percentage
FROM
    payments
GROUP BY
    payment_status;
"""

failed_payments_summary = pd.read_sql(query, conn)
print("Payment Status Breakdown:")
print(failed_payments_summary)

"""**4. Order Details**

a. Unpaid Orders
"""

query = """
SELECT
    o.order_id,
    o.customer_id,
    o.order_amount,
    o.order_status
FROM
    orders o
LEFT JOIN
    (SELECT order_id FROM payments WHERE payment_status = 'Completed') p
    ON o.order_id = p.order_id
WHERE
    p.order_id IS NULL;
"""

unpaid_orders = pd.read_sql(query, conn)
print("Unpaid Orders:")
print(unpaid_orders.head())

"""b. Failed Payments

"""

query = """
SELECT
    o.order_id,
    o.customer_id,
    o.order_date,
    o.order_status,
    p.payment_status,
    p.payment_method,
    p.payment_amount
FROM
    orders o
LEFT JOIN
    payments p ON o.order_id = p.order_id
WHERE
    p.payment_status IS NULL OR p.payment_status != 'completed';
"""

# Run the query
unpaid_orders_failed = pd.read_sql(query, conn)
print("Unpaid or Failed Orders:")
print(unpaid_orders_failed.head())

"""c. Monthly Orders and Monthly Revenue"""

query = """
SELECT
    strftime('%Y-%m', order_date) AS order_month,
    COUNT(*) AS total_orders
FROM
    orders
GROUP BY
    order_month
ORDER BY
    order_month;
"""

monthly_orders = pd.read_sql(query, conn)
print("Monthly Orders:")
print(monthly_orders)

query = """
SELECT
    strftime('%Y-%m', payment_date) AS payment_month,
    SUM(payment_amount) AS total_revenue
FROM
    payments
WHERE
    payment_status = 'completed'
GROUP BY
    payment_month
ORDER BY
    payment_month;
"""

monthly_revenue = pd.read_sql(query, conn)
print("Monthly Revenue:")
print(monthly_revenue)

query = """
SELECT
    STRFTIME('%Y-%m', o.order_date) AS month,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(p.payment_amount) AS total_revenue
FROM
    orders o
JOIN
    payments p ON o.order_id = p.order_id
WHERE
    p.payment_status = 'completed'
GROUP BY
    month
ORDER BY
    month;
"""

monthly_trends = pd.read_sql(query, conn)
print("Monthly Trends:")
print(monthly_trends)

"""**Exporting files for use in Tableau**"""

customer_summary.to_csv("customer_summary.csv", index=False)

unpaid_orders.to_csv("unpaid_orders.csv", index=False)

monthly_trends.to_csv("monthly_trends.csv", index=False)

print("All files exported successfully.")

unpaid_orders_failed.to_csv("unpaid_orders_failed.csv", index=False)